name = "itsfrank/frktmpl"
version = "0.1.0"
description = "niche templating system for processing luau source code"
authors = ["Francis O'Brien <github.com/itsfrank>"]
license = "MIT"
includes = [
    "src",
    "pesde.toml",
    "README.md",
    "LICENSE",
    ".luaurc",
]

[target]
environment = "lune"
lib = "src/_pesde_init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dev_dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.1" }
